- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install pip && venv"
  shell: |
    sudo apt install -y python3-pip
    sudo apt install -y python3-venv

- name: "install docker"
  shell: |
    sudo apt-get install -y docker.io

- name: "start docker"
  shell: |
    sudo service docker start

- name: "test docker"
  shell: |
    sudo docker run hello-world
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"