- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install pip && venv"
  shell: |
    sudo apt install -y python3-pip
    sudo apt install -y python3-venv

- name: "install docker"
  shell: |
    sudo apt-get install -y docker.io

- name: "start docker"
  shell: |
    # sudo groupadd docker
    # sudo usermod -aG docker $USER
    # newgrp docker
    sudo service docker start

- name: "test docker"
  shell: |
    docker run hello-world
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "install kubectl"
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: "install minikube"
  shell: |
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
    && chmod +x minikube
    sudo install minikube /usr/local/bin/