# Generated by Django 4.2.4 on 2023-08-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='song_slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
